language: generic

sudo: false

install:
  - git clone --depth=1 https://github.com/thinca/vim-themis /tmp/themis
  - git clone https://github.com/vim/vim $HOME/vim
  - (if ! test -d $HOME/vim-$VIM_VERSION/bin; then cd $HOME/vim && git checkout . && git checkout v$VIM_VERSION && ./configure --prefix=$HOME/vim-$VIM_VERSION && make && make install; fi)

cache:
  directories:
    - $HOME/vim-$VIM_VERSION

env:
  - VIM_VERSION=8.0.0000 PATH=$HOME/vim-$VIM_VERSION/bin/:$PATH
  - VIM_VERSION=7.4 PATH=$HOME/vim-$VIM_VERSION/bin/:$PATH
  - VIM_VERSION=7.3 PATH=$HOME/vim-$VIM_VERSION/bin/:$PATH

script:
  - vim --version
  - /tmp/themis/bin/themis --reporter spec
